### ISSUE TITLE
Nothing shown whiling executing the algorithm

### ISSUE THREAD

**Issue by SandW** [ethz-asl/StructuralInspectionPlanner#5]
I followed your wiki instructions and configured the rviz as you mentioned. However, there was nothing shown in the rviz after I executed the launch cmd and rosrun cmd.

![screenshot from 2015-08-14 11 11 32](https://cloud.githubusercontent.com/assets/6024463/9266547/415baa38-4275-11e5-8d0e-6afac39e2559.png)

**Comment by SandW** [comment]
It is the starting sequence problem.
The right sequence should be:
1. launch
2. rviz(configure the topic properly)
3. rosrun
Then everything is good!

**Comment by birchera** [comment]
The reason that otherwise it doesn't work is, that you need a roscore running. You can either start it by typing 'roscore' in a seperate shell first or it is started automatically once you invoke the launch command.
Note that you can save the configuration of rviz, such that you don't need to set it up every time.
